# Site settings
title: Hana Choi - University of Rochester
description: Hana Choi, Rochester, Marketing, Simon
keywords: Hana Choi, Rochester, Marketing, Simon
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://hanachoi.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
